echo "SELAMAT DATANG DI VERSI TERBARU TOOLS INI!" | lolcat
echo "DI BUAT OLEH SATU ORANG YAITU SAYA SENDIRI" | lolcat
echo "PERKENALKAN NAMA KU ZCYBORG (SAMARAN)" | lolcat
echo "NICKNAME KU Zcyb0RG" | lolcat
echo "SEKARANG KALIAN BISA PAKAI TOOLS INI SECARA GRATIS GAK BAYAR!!!" | lolcat
echo "PERTANYAAN TENTANG PASSWORD GAK AKAN DI RESPON!" | lolcat
sleep 8

